"""Initial Migration

Revision ID: 1402f209860b
Revises: d38ac362094b
Create Date: 2022-05-04 16:27:05.548626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1402f209860b'
down_revision = 'd38ac362094b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
